kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eng-sres-admin
  namespace: eng
subjects:
- kind: Group
  name: eng-sre@foo-corp.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
